<a href="https://colab.research.google.com/github/fraygoezdavid/Lenguajes_de_programacion/blob/main/Proyecto_Cripto_Entregable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#INSTITUTO TECNOLÓGICO METROPOLITANO
Ingeniería Financiera
VII Concurso de Analítica Financiera
The Trading Floor Experience
Criptomonedas
Jueves 21 de mayo de 2026 · Centro Cultural ITM
GUÍA PARA EQUIPOS PARTICIPANTES

###_¿Qué es este concurso?_
Cada equipo actúa como un fondo de inversión en criptomonedas. Su misión es construir una aplicación
interactiva que analice datos históricos, proponga una idea de trading y la defienda ante inversionistas
reales el día del evento.
Los asistentes al evento son los inversionistas. Ellos recorren los stands, ven la app en vivo, escuchan
el pitch de cada fondo y deciden dónde poner su capital ficticio. El fondo que mejor explique su propuesta
capta más inversión.
###_Lo que deben construir_
Una aplicación interactiva en R o Python que descargue datos en tiempo real desde Yahoo Finance el
día del evento. No se permiten archivos CSV precargados: la app debe conectarse a la fuente en vivo.

In [24]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.9.6)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.5)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.4.22)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (13.9.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.7->yfinance) (0.1.2)

In [69]:
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.express as px

print("¡Listo para analizar cripto!")

¡Listo para analizar cripto!

#Criptomonedas Disponibles
- Tickers a utilizar\

In [75]:
Cripto = {
    'Criptomonedas': ['Bitcoin', 'Ethereum ', 'Solana', 'Cardano', 'Litecoin'],
    'Simbolo': ['BTC-USD', 'ETH-USD', 'SOL-USD', 'ADA-USD', 'LTC-USD'],
    'Categoria': ['Alta capitalización', 'Alta capitalización', 'Capitalización media', 'Capitalización media', 'Capitalización media']
}
# Creación del DataFrame
df = pd.DataFrame(Cripto)

# Mostramos el DataFrame
df

  Criptomonedas  Simbolo             Categoria
0       Bitcoin  BTC-USD   Alta capitalización
1     Ethereum   ETH-USD   Alta capitalización
2        Solana  SOL-USD  Capitalización media
3       Cardano  ADA-USD  Capitalización media
4      Litecoin  LTC-USD  Capitalización media

In [47]:
tickers = ['BTC-USD', 'ETH-USD', 'SOL-USD', 'ADA-USD', 'LTC-USD' ]

#Descargar los datos

In [65]:
btc = yf.download (tickers, start='2026-01-01', end='2026-05-12', interval='1d')
btc.head()

/tmp/ipykernel_25198/1257540757.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  btc = yf.download (tickers, start='2026-01-01', end='2026-05-12', interval='1d')
[*********************100%***********************]  4 of 4 completed

Price          Close                                             High  \
Ticker       ADA-USD       BTC-USD      ETH-USD     SOL-USD   ADA-USD
Date
2026-01-01  0.356212  88731.984375  3000.394287  126.761124  0.358887
2026-01-02  0.393758  89944.695312  3124.422607  132.133667  0.395642
2026-01-03  0.389375  90603.187500  3125.917480  133.298477  0.398342
2026-01-04  0.400091  91413.492188  3140.710449  133.899612  0.404308
2026-01-05  0.421874  93882.554688  3226.130371  137.989975  0.424610

Price                                                   Low                \
Ticker           BTC-USD      ETH-USD     SOL-USD   ADA-USD       BTC-USD
Date
2026-01-01  88803.226562  3006.010254  126.987114  0.331777  87399.406250
2026-01-02  90884.460938  3146.984375  132.987900  0.354759  88298.617188
2026-01-03  90679.570312  3135.025635  133.608383  0.383625  89328.070312
2026-01-04  91712.585938  3160.551025  135.354477  0.389192  90595.101562
2026-01-05  94762.070312  3261.245850  139.635590  0.395653  91414.625000

Price                                    Open                             \
Ticker          ETH-USD     SOL-USD   ADA-USD       BTC-USD      ETH-USD
Date
2026-01-01  2966.845215  124.051537  0.332836  87508.046875  2966.997314
2026-01-02  2989.901367  125.791222  0.356212  88733.062500  3000.453125
2026-01-03  3077.465820  129.935211  0.393761  89945.054688  3124.310303
2026-01-04  3119.427490  133.227325  0.389380  90603.000000  3125.960205
2026-01-05  3134.092773  133.348663  0.400092  91414.625000  3141.486328

Price                      Volume
Ticker         SOL-USD    ADA-USD      BTC-USD      ETH-USD     SOL-USD
Date
2026-01-01  124.484741  531808672  18849043990  10268796662  2461653813
2026-01-02  126.761124  968787318  46398906171  25242778003  4508641946
2026-01-03  132.133392  546995635  20774828592  11460707919  2477037555
2026-01-04  133.298218  646307408  26770491368  13890479323  2982580991
2026-01-05  133.902634  905549791  53376407252  27211995956  5200675282

In [ ]:
eth = yf.download ('ETH-USD', start='2026-01-01', end='2026-05-12', interval='1d')
eth.head()

In [ ]:
sol = yf.download ('SOL-USD', start='2026-01-01', end='2026-05-12', interval='1d')
sol.head()

In [ ]:
ada = yf.download ('ADA-USD', start='2026-01-01', end='2026-05-12', interval='1d')
ada.head()

In [ ]:
ltc = yf.download ('LTC-USD', start='2026-01-01', end='2026-05-12', interval='1d')
ltc.head()

In [51]:
btc.head(5)

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Date,,,,,
2024-01-01,44167.332031,44175.437500,42214.976562,42280.234375,18426978443
2024-01-02,44957.968750,45899.707031,44176.949219,44187.140625,39335274536
2024-01-03,42848.175781,45503.242188,40813.535156,44961.601562,46342323118
2024-01-04,44179.921875,44770.023438,42675.175781,42855.816406,30448091210
2024-01-05,44162.691406,44353.285156,42784.718750,44192.980469,32336029347

In [50]:
btc.describe()

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
count,365.000000,365.000000,365.000000,365.000000,3.650000e+02
mean,65888.868290,67114.172517,64434.563699,65751.583765,3.742215e+10
std,14632.134647,14920.310187,14310.209801,14618.657810,2.196309e+10
min,39507.367188,40127.351562,38521.894531,39518.714844,9.344044e+09
25%,59027.625000,60262.718750,57650.113281,59014.988281,2.384281e+10
50%,64118.792969,65523.222656,62783.632812,64104.738281,3.229276e+10
75%,69122.335938,70046.273438,67535.132812,69020.546875,4.314798e+10
max,106140.601562,108268.445312,105291.734375,106147.296875,1.492189e+11

In [32]:
btc.columns

MultiIndex([( 'Close', 'BTC-USD'),
            (  'High', 'BTC-USD'),
            (   'Low', 'BTC-USD'),
            (  'Open', 'BTC-USD'),
            ('Volume', 'BTC-USD')],
           names=['Price', 'Ticker'])

In [33]:

btc.shape

(365, 5)

#Riesgo: volatilidad anualizada
- La volatilidad mide cuánto varía un activo. Anualizarla permite comparar entre activos y horizontes.
- Calcula la volatilidad anualizada (desviación estándar × √252 días bursátiles).

In [34]:
vol_anual = btc['retorno'].std(1) * np.sqrt(252)

KeyError: 'retorno'

#Visualización de precios y retornos (Graficos)
- Un buen gráfico vale más que mil tablas — el jurado lo agradecerá.

In [22]:
# Línea de precios
fig = px.line(df, y='Close', title='Bitcoin 2024')
fig.show()

# Histograma de retornos
fig2 = px.histogram(df, x='retorno', nbins=50)
fig2.show()

NameError: name 'df' is not defined

#Matriz de correlación
- Si dos cripto se mueven igual (corr ≈ 1), no diversificas. Busca pares con baja correlación.

In [23]:
# Calcular correlación
returns = pd.DataFrame({
  'BTC': btc['Close'].pct_change(),
  'ETH': eth['Close'].pct_change(),
  'SOL': sol['Close'].pct_change(),
  'ADA': ada['Close'].pct_change(),
})
corr = returns.corr()

import seaborn as sns
sns.heatmap(corr, annot=True, cmap='coolwarm')

NameError: name 'eth' is not defined

#Recomendación al inversor
- Selecciona el perfil del inversor y verás qué portafolio tiene sentido recomendar.
- La entrega final del reto: una recomendación clara, basada en datos, comprensible para alguien sin formación financiera.